CXX=g++
CXXFLAGS=-g -Wall 
SUNFLAGS= -lsocket -lnsl -lresolv

# Uncomment for parser DEBUG
#DEFS=-DDEBUG

#OBJS=server1.o

all: server1

# SERVER 1  ============================================
server1: server1.cpp
	$(CXX) -o server1 server1.cpp $(SUNFLAGS)


# SERVER 2  ============================================



# SERVER 3  ============================================


clean:
	rm -f *.o server1
